language: rust
os:
    - windows
    - linux
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
cache: cargo
script:
    - cargo build --release
deploy:
    provider: releases
    skip_cleanup: true
    api_key:
        secure: PPKtpvWrTgPG4OQqOadgTqLAvyIL/JW1eK5B1bWLDPcUi8SH5driu3dHrCQmc3epDgW8nq5lsW0+U0ACcaIFs9eoh0blYAh3KAQNzTDk2HDF3tf+1X0KRKSva1zYCe3J5egGtBDlhvI6HJUCMYDYk/M++pP8OE3l2/1wWb8PntttGTochz6pw4TPLS7npXkaIkV1Kb7Y2pCBoRAdflR7YAXr3cPI0pjY4TbXfZ7a6sT8hLEmtpiCs+8U64f2gyinIAph5sWv5r005WAQYiCT/c4m0KRBWoYneFVL3QYdsj9fHX8mtJ/UPPb6z5MtPg7yuly/7Hfl20eFtZ64jEkc8+IeMXjwSpb2fba6ODSPTgCHbipHgHAOnzLvLJhLRT65eUFer8Ug4ZFQCYtgXyAiF9oaka405gzDvoo7H2+73wjQlgZm505FJp8au7/R3ZJIH6q3tc4phDtzXFU2/m5OMvFA7Kc8f0ZHSS6I7j5ypBpCKtdHwAJmG3Kwjz1klN9ugK4objSIv78eE1QWDilD3QuWp18ESHhjRZN7XheLhw8V34N/XqwPlJicDLk9bK3KqGkRmnA/0p8v017P/9HhNSvPFqBr8xpUYb1M5vpDAuCYXmUj41IzrydGHhxTlQts/iC4N7eOCHWW6J52RgfXewaCtNB8p3OQ6MYfvgpYyyA=
    file:
        - "target/release/gitweb"
        - "target/release/gitweb.exe"
    on:
        repo: yoannfleurydev/gitweb
        tags: true
