language: rust
os:
    - windows
    - linux
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
script:
    - cargo build --release
deploy:
    provider: releases
    skip_cleanup: true
    api_key:
        secure: dQsgKbrB3L1YouTeahHSWKdnY2FvLNsZRuxS0swlgg2jhcZbVVNwwU/qqgadiYKgf9B+XBnSvW4lWQgFiMDf2hSw7SE+mXg8e5gXEiZJI+IadCUEvj3GwTGo5TtT/zDb/3KyZvD0X4q8FlzFZE1K+I/BDXy4O/awMsXdS85CCqlEiz16Ao4GFLUtAJrKjLHtl9HCQgGBvJaanxxGMg+E4Bu/CWJYw7ecThIAKZpW20Jyeq8hWgDLnRwfWcRoxRyx1GX0BcVU4BGpXSovHDNpfDIIVpa6OMrZXYDFs0yXXoa7kxvlhf6tKcjrWkTtguczWECEtCP9dJgtqU3YJEE1Wn8q9a0zKKy+1jb1ysCdn+7ExlnphJ91KLMaP5x9O1E2W6bxFNIWy51Tq+19647O8FaNQ81mXSZo7Ao873PrzHW3Bk2xNaEKItSE0mdyV8s+dZJwQBSeD2/3EcMBjfP9IbpJ9ol+yEV3qWZvlcd7mKVi2hokNXh0JkxPJajQJo0S4twRXw8o+Z0okfD7TGBaQJO0oZjJ9691He0SbkEFnF2pYRRp2IndKRUa59sW50Nfip87sSu7SUNBLuKF5K1728bdkp2N9XfSh0WulAkU37nNIno3cgnqt3/ouDZ3735mmVym7KWx7ywLHhzCKjxr84uQDpkEj/t0iDi5Oqt+PXI=
    file:
        - "target/release/gitweb"
        - "target/release/gitweb.exe"
    on:
        repo: yoannfleurydev/gitweb
        tags: true
