name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish_on_crates_io:
    name: Publish on crates.io
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: login
          args: ${{ secrets.CRATES_IO_TOKEN_GITWEB }}
      - name: Package the crate
        uses: actions-rs/cargo@v1
        with:
          command: package
      - name: Publish the crate
        uses: actions-rs/cargo@v1
        with:
          command: publish
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

  release_linux:
    needs: publish_on_crates_io
    name: Linux Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linux Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Release Asset Linux
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.publish_on_crates_io.outputs.upload_url }}
          asset_path: ./target/release/gitweb
          asset_name: gitweb-linux
          asset_content_type: application/x-sharedlib

  release_windows:
    needs: publish_on_crates_io
    name: Windows Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Windows Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Release Asset Windows
        id: upload-release-asset-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.publish_on_crates_io.outputs.upload_url }}
          asset_path: ./target/release/gitweb.exe
          asset_name: gitweb-windows.exe
          asset_content_type: application/x-dosexec

  release_macos:
    needs: publish_on_crates_io
    name: MacOS Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: MacOS Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Release Asset MacOS
        id: upload-release-asset-macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.publish_on_crates_io.outputs.upload_url }}
          asset_path: ./target/release/gitweb
          asset_name: gitweb-macos
          asset_content_type: application/x-mach-binary
